version: '2'
services:
    app:
        build: .
        image: billym/exchange-rates
        ports:
            - '8080:8080'
        volumes:
            - './app/src:/app/src'
            - './app/static:/app/static'
